WIP: Encode ITU-WHO T-FG-AI4H document
metanorma/mn-samples-itu pull request #156
Opened 2022-10-15 20:51 UTC by anermina

Notes:
- "References" title has been changed to "Bibliography", because "References" is used for normative references, which cannot have a numeric identifier in ITU flavor. All the references here have a numeric identifier.
- Ticket https://github.com/metanorma/metanorma-itu/issues/333 has been opened to address the usage of Box elements.

2022-10-16 07:40 UTC, ronaldtse requested changes
There are two attributes to remove, and can we split this file into separate sections? Thanks!

2022-10-16 07:40 UTC, ronaldtse commented on sources/T-FG-AI4H-2022-MSW-E.adoc
> +:docfile: T-FG-AI4H-2022-MSW-E.adoc
@anermina we no longer need the `docfile` attribute, and it is deprecated, please always remove it. thanks!

2022-10-16 07:40 UTC, ronaldtse commented on sources/T-FG-AI4H-2022-MSW-E.adoc
> +:data-uri-image:
Let's remove `data-uri-image` because it is now enabled by default. Thanks!

2022-10-16 19:29 UTC, anermina commented
Thank you @ronaldtse! Changes have been applied.

I addressed several new tickets in the meanwhile. They are listed in the notes of this PR.
However, there is still one unclarity regarding the front page, i.e. document identifiers which should be used for `:doctype: focus-group`. Currently, we have the following differences (one regarding the `series` attribute has been addressed in a ticket):
![image](https://user-images.githubusercontent.com/55683568/196054186-4a408f60-63b6-45ab-b293-03631d7ac252.png)

2022-10-20 17:00 UTC, ronaldtse commented
Thank you @anermina ! Let's merge this first and then keep the pending tasks as a separate issue.

2022-10-20 17:01 UTC, ronaldtse approved these changes

2022-10-20 17:01 UTC, merged

2022-10-21 10:12 UTC, bquast commented
Dear colleagues, thank you very much. I will distribute it to our delegates.

2022-10-22 05:01 UTC, ronaldtse commented
Thanks @bquast 👍